// <auto-generated />
using System;
using DiscordBotHost.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiscordBotHost.EntityFramework.Migrations
{
    [DbContext(typeof(DiscordBotDbContext))]
    partial class DiscordBotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiscordBotHost.EntityFramework.User", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<decimal>("DiscordUserId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("FirebaseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LinksChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DiscordBotHost.Features.Auditions.Opportunity", b =>
                {
                    b.Property<int>("OpportunityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OpportunityId"));

                    b.Property<DateTimeOffset?>("AuditionDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("AuditionEndDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShowName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OpportunityId");

                    b.ToTable("Opportunities");
                });

            modelBuilder.Entity("DiscordBotHost.Features.ContentMonitor.UrlContentInspection", b =>
                {
                    b.Property<int>("UrlContentInspectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UrlContentInspectionId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Differences")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ThresholdExceeded")
                        .HasColumnType("bit");

                    b.Property<int>("UrlContentMonitorRequestId")
                        .HasColumnType("int");

                    b.HasKey("UrlContentInspectionId");

                    b.HasIndex("UrlContentMonitorRequestId");

                    b.ToTable("ContentInspections");
                });

            modelBuilder.Entity("DiscordBotHost.Features.ContentMonitor.UrlContentMonitorRequest", b =>
                {
                    b.Property<int>("UrlContentMonitorRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UrlContentMonitorRequestId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("DifferenceThreshold")
                        .HasColumnType("float");

                    b.Property<decimal>("DiscordUserId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<long>("Interval")
                        .HasColumnType("bigint");

                    b.Property<int>("Repeat")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("RunUntil")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Selectors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UrlContentMonitorRequestId");

                    b.ToTable("ContentMonitorRequests");
                });

            modelBuilder.Entity("DiscordBotHost.Features.ContentMonitor.UrlContentInspection", b =>
                {
                    b.HasOne("DiscordBotHost.Features.ContentMonitor.UrlContentMonitorRequest", "UrlContentMonitorRequest")
                        .WithMany()
                        .HasForeignKey("UrlContentMonitorRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UrlContentMonitorRequest");
                });
#pragma warning restore 612, 618
        }
    }
}
